/**
 * Signed token helpers for the NPS flow.
 *
 * Two token types:
 *
 *   invite token (`t`)  - generated by n8n, embedded in the email links.
 *                         Identifies the customer without putting their email
 *                         address in the URL. Valid for 30 days.
 *
 *   submit token (`st`) - generated by the confirmation page, bound to the
 *                         invite token and the chosen score. Injected into the
 *                         form by JavaScript, so a link scanner that parses
 *                         HTML without executing it cannot produce one.
 *
 * Both are `base64url(json).base64url(hmac-sha256)`.
 */

import crypto from 'node:crypto';

export const INVITE_TTL_MS = 30 * 24 * 60 * 60 * 1000; // 30 days
export const SUBMIT_TTL_MS = 30 * 60 * 1000; // 30 minutes

/**
 * Minimum time between the confirmation page being served and the vote landing.
 * A human has to read the page and press a button; automated form submitters
 * fire immediately.
 */
export const MIN_DWELL_MS = 1200;

const b64url = (value) => Buffer.from(value).toString('base64url');
const unb64url = (value) => Buffer.from(value, 'base64url').toString('utf8');

const sign = (body, secret) =>
  crypto.createHmac('sha256', secret).update(body).digest('base64url');

function safeEqual(a, b) {
  const left = Buffer.from(String(a));
  const right = Buffer.from(String(b));
  if (left.length !== right.length) return false;
  return crypto.timingSafeEqual(left, right);
}

/** Constant-time string comparison for shared secrets and API keys. */
export function timingSafeCompare(a, b) {
  if (typeof a !== 'string' || typeof b !== 'string' || a.length === 0 || b.length === 0) {
    return false;
  }
  // Hash first so differing lengths don't short-circuit and leak length.
  const digest = (value) => crypto.createHash('sha256').update(value).digest();
  return crypto.timingSafeEqual(digest(a), digest(b));
}

function unpack(token, secret) {
  if (typeof token !== 'string' || token.length < 8) return null;
  const split = token.lastIndexOf('.');
  if (split <= 0) return null;

  const body = token.slice(0, split);
  const signature = token.slice(split + 1);
  if (!safeEqual(signature, sign(body, secret))) return null;

  try {
    return JSON.parse(unb64url(body));
  } catch {
    return null;
  }
}

/**
 * Score arrives from the query string. Anything that is not a bare integer
 * 0-10 is rejected outright, which is also what keeps it out of the HTML.
 */
export function parseScore(raw) {
  if (typeof raw !== 'string' && typeof raw !== 'number') return null;
  const trimmed = String(raw).trim();
  if (!/^(10|[0-9])$/.test(trimmed)) return null;
  return Number(trimmed);
}

export function escapeHtml(value) {
  return String(value).replace(
    /[&<>"']/g,
    (char) =>
      ({
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;',
        "'": '&#39;',
      })[char],
  );
}

export function createInviteToken({ customer, email, record }, secret, now = Date.now()) {
  if (!customer || !email) throw new Error('customer and email are required');
  const body = b64url(
    JSON.stringify({ c: String(customer), e: String(email), r: record ? String(record) : '', i: now }),
  );
  return `${body}.${sign(body, secret)}`;
}

export function verifyInviteToken(token, secret, now = Date.now()) {
  const payload = unpack(token, secret);
  if (!payload) return { ok: false, reason: 'invalid' };
  if (typeof payload.i !== 'number') return { ok: false, reason: 'invalid' };
  if (now - payload.i > INVITE_TTL_MS) return { ok: false, reason: 'expired' };
  if (now - payload.i < -60_000) return { ok: false, reason: 'invalid' }; // clock skew guard
  if (!payload.c || !payload.e) return { ok: false, reason: 'invalid' };

  return {
    ok: true,
    customer: String(payload.c),
    email: String(payload.e),
    record: payload.r ? String(payload.r) : '',
    issuedAt: payload.i,
  };
}

const fingerprint = (inviteToken) =>
  crypto.createHash('sha256').update(inviteToken).digest('base64url').slice(0, 22);

export function createSubmitToken(inviteToken, score, secret, now = Date.now()) {
  const body = b64url(JSON.stringify({ h: fingerprint(inviteToken), s: score, i: now }));
  return `${body}.${sign(body, secret)}`;
}

export function verifySubmitToken(submitToken, inviteToken, score, secret, now = Date.now()) {
  const payload = unpack(submitToken, secret);
  if (!payload) return { ok: false, reason: 'invalid' };
  if (payload.s !== score) return { ok: false, reason: 'score_mismatch' };
  if (payload.h !== fingerprint(inviteToken)) return { ok: false, reason: 'token_mismatch' };

  const age = now - payload.i;
  if (typeof payload.i !== 'number' || age > SUBMIT_TTL_MS) return { ok: false, reason: 'expired' };
  if (age < MIN_DWELL_MS) return { ok: false, reason: 'too_fast' };

  return { ok: true, issuedAt: payload.i };
}

/**
 * Signature for the server-to-server call into Apps Script, so the Apps Script
 * endpoint only accepts writes that came through this function.
 */
export function signVote({ score, customer, email, record, ts }, secret) {
  const canonical = [score, customer, email, record || '', ts].join('|');
  return crypto.createHmac('sha256', secret).update(canonical).digest('base64url');
}
